### PR TITLE
Make Travis tests pass

### PR DESCRIPTION
**Pull request by jeunito**
@nicolaracco as requested. Please do not merge yet as it is still a work in progress. We'll see what else needs to be fixed after Travis runs.

### CODE REVIEW

**Comment by jeunito** [comment]
@nicolaracco the tests are passing now

**Comment by nicolaracco** [comment]
Hey @jeunito, thank you a lot for your work. Just one doubt I have: do we need that `openapi` config parameter? It seems to not be used by the code, but just initialized during specs.

**Comment by jeunito** [comment]
@nicolaracco yes it's needed to configure openapi parameters although. It is merged in the output of  [```AkamaiApi.auth```](https://github.com/AppLovin/akamai_api/blob/bug/fp_pass/lib/akamai_api.rb#L29)

**Comment by jeunito** [comment]
@nicolaracco I have updated the documentation in README.md

**Pull request merged**
